<?php session_start(); ?>
<html>
<head>
    <meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="activityStyle.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
    <title></title>




    <!-- #region Jssor Slider Begin -->

    <!-- Generated by Jssor Slider Maker Online. -->
    <!-- This demo works with jquery library -->

    <!-- use jssor.slider.debug.js instead for debug -->
    <script>
			function Event(n, e) {
				if (e == "true") {
					document.getElementById(n.id).style.overflow = "visible";
				} else {
					document.getElementById(n.id).style.overflow = "hidden";
				}
			}
			
        jQuery(document).ready(function ($) {
            
            var jssor_1_SlideoTransitions = [
              [{b:0.0,d:600.0,y:-290.0,e:{y:27.0}}],
              [{b:0.0,d:1000.0,y:185.0},{b:1000.0,d:500.0,o:-1.0},{b:1500.0,d:500.0,o:1.0},{b:2000.0,d:1500.0,r:360.0},{b:3500.0,d:1000.0,rX:30.0},{b:4500.0,d:500.0,rX:-30.0},{b:5000.0,d:1000.0,rY:30.0},{b:6000.0,d:500.0,rY:-30.0},{b:6500.0,d:500.0,sX:1.0},{b:7000.0,d:500.0,sX:-1.0},{b:7500.0,d:500.0,sY:1.0},{b:8000.0,d:500.0,sY:-1.0},{b:8500.0,d:500.0,kX:30.0},{b:9000.0,d:500.0,kX:-30.0},{b:9500.0,d:500.0,kY:30.0},{b:10000.0,d:500.0,kY:-30.0},{b:10500.0,d:500.0,c:{x:87.50,t:-87.50}},{b:11000.0,d:500.0,c:{x:-87.50,t:87.50}}],
              [{b:0.0,d:600.0,x:410.0,e:{x:27.0}}],
              [{b:-1.0,d:1.0,o:-1.0},{b:0.0,d:600.0,o:1.0,e:{o:5.0}}],
              [{b:-1.0,d:1.0,c:{x:175.0,t:-175.0}},{b:0.0,d:800.0,c:{x:-175.0,t:175.0},e:{c:{x:7.0,t:7.0}}}],
              [{b:-1.0,d:1.0,o:-1.0},{b:0.0,d:600.0,x:-570.0,o:1.0,e:{x:6.0}}],
              [{b:-1.0,d:1.0,o:-1.0,r:-180.0},{b:0.0,d:800.0,o:1.0,r:180.0,e:{r:7.0}}],
              [{b:0.0,d:1000.0,y:80.0,e:{y:24.0}},{b:1000.0,d:1100.0,x:570.0,y:170.0,o:-1.0,r:30.0,sX:9.0,sY:9.0,e:{x:2.0,y:6.0,r:1.0,sX:5.0,sY:5.0}}],
              [{b:2000.0,d:600.0,rY:30.0}],
              [{b:0.0,d:500.0,x:-105.0},{b:500.0,d:500.0,x:230.0},{b:1000.0,d:500.0,y:-120.0},{b:1500.0,d:500.0,x:-70.0,y:120.0},{b:2600.0,d:500.0,y:-80.0},{b:3100.0,d:900.0,y:160.0,e:{y:24.0}}],
              [{b:0.0,d:1000.0,o:-0.4,rX:2.0,rY:1.0},{b:1000.0,d:1000.0,rY:1.0},{b:2000.0,d:1000.0,rX:-1.0},{b:3000.0,d:1000.0,rY:-1.0},{b:4000.0,d:1000.0,o:0.4,rX:-1.0,rY:-1.0}]
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $Idle: 2000,
              $CaptionSliderOptions: {
                $Class: $JssorCaptionSlideo$,
                $Transitions: jssor_1_SlideoTransitions,
                $Breaks: [
                  [{d:2000,b:1000}]
                ]
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizes
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 600);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
    </script>
	


 
	</head>
<body>
<div id="frame">
	<div id="wrapper">
	<div id="title">
				<img id="name" style="width:290px;height:100px;margin-left:60px;margin-top:15px;" src="banner_logo.png">

				<ul id="apDiv1"  onmouseover="Event(this,'true');" onmouseout="Event(this,'');">
					<li>
						<a id="apDiv1_1" href="../Home.php">關於我</a>
					</li>
					<li>
						<a class="bar" href="../Self.php">關於自己&nbsp &nbsp</a>
					</li>
					<li>
						<a class="bar" href="../test.php">測試結果&nbsp &nbsp</a>
					</li>
					<li>
						<a class="bar" href="../match.php">開始配對&nbsp &nbsp </a>
					</li>
					<li>
						<a class="bar" href="../help.php">愛情急診室  </a>
					</li>
					
				</ul>
				<ul id="apDiv2" onmouseover="Event(this,'true');" onmouseout="Event(this,'');">
					<li>
					<a id="apDiv2_1" href="../slide/main.php">腦波/腦部測試系統</a>
						
					</li>
					
					<li>
						<a class="bar" href="../slide/brain.php">腦波測試系統</a>
					</li>
					<li>
						<a class="bar" href="../slide/main.php#secondPage">臉部測試系統</a>
					</li>
					
				</ul>
				<ul id="apDiv3" onmouseover="Event(this,'true');" onmouseout="Event(this,'');">
					
					<li>
					<a id="apDiv3_1" href="activity.php">活動專區</a>	
					</li>

				</ul>
				<ul id="apDiv4" onmouseover="Event(this,'true');" onmouseout="Event(this,'');">
					<li>
					<a id="apDiv4_1" href="../Disvote.php">投票議題討論區</a>						
					</li>
					<li>				
					<a class="bar" href="../vote.php">投票議題區</a>				
					</li>		
					<li>				
					<a class="bar" href="../articledisscuss.php">議題討論區</a>					
					</li>
				</ul>
				<ul id="apDiv5">
					<li>
					<a id="apDiv5_1" href="../main.html">Home</a>
					</li>					
				</ul>
			<?php 
				error_reporting(0);
				if($_SESSION['username'] != null){
					echo '<a style="position:absolute;margin-left:700px;margin-top:58px;text-decoration:none" href="logout.php"  id="apDiv6_1">登出</a>  <br><br>';
				}				
			?>
			</div>
		
		</ul>
	
		<div style=" margin-left:0px; display:inline">
		<a href="activity.php"><div class="boxes" style="display:inline;position:absolute; margin-top:100px;"><p class="boxes_word">聯誼活動</p></div></a>
		<br>
		<a href="team.php"><div class="boxes" style="display:inline;position:absolute; margin-top:150px;"><p class="boxes_word">團體聯誼</p></div></a>
		<br>
		<a href="lesson.php"><div class="boxes" style="display:inline;position:absolute; margin-top:200px;"><p class="boxes_word">跨界課程</p></div></a>
		<br>
		<a href="produce.php"><div class="boxes" style="display:inline;position:absolute; margin-top:250px;"><p class="boxes_word">客製約會</p></div></a>
		
		<div id="jssor_1" style="position: relative; margin: 0 auto; top: -10px; left: 0px; width: 860px; height: 300px; overflow: hidden; visibility: hidden;">
        <!-- Loading Screen -->
        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
            <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
        </div>
        <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 80px; width: 806px; height: 376px; overflow: hidden;">
            <div data-p="112.50" style="display: none;">
               <img data-u="image" src="img/img001.JPG" />
            </div>
			
            <div data-p="112.50" style="display: none;">
               <img data-u="image" src="img/img002.jpg" />
            </div>
			
            <div data-p="112.50" style="display: none;">
              <img data-u="image" src="img/img003.jpg" />
            </div>
			
            <div data-p="112.50" style="display: none;">
                <img data-u="image" src="img/img008.jpg" />
             
            </div>
           
            
            <div data-p="112.50" style="display: none;">
             <img data-u="image" src="img/img000.jpg" />
				
            </div>
        </div>
        <!-- Bullet Navigator -->
        <div data-u="navigator" class="jssorb01" style="bottom:16px;right:10px;">
            <div data-u="prototype" style="width:12px;height:12px;"></div>
        </div>
        <!-- Arrow Navigator -->
        <span data-u="arrowleft" class="jssora02l" style="top:123px;left:88px;width:55px;height:55px;" data-autocenter="2"></span>
        <span data-u="arrowright" class="jssora02r" style="top:123px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
  
		</div>

    <!-- #endregion Jssor Slider End -->
		</div>
		
		
		 <div id="content">
			<div id="left">
				<p id="activity1_title">
					活動進行中
				</p>	
				
			<img id="leftbox1" style="width:304px;height:209px;margin-left:200px;" src="pic1.jpg"> 
			
			</div>
			
			
	 
			<div id="right">
			<h2 style="display:inline-block"> &nbsp &nbsp &nbsp《秋季一對一約會》</h2>
			<br> 
				<br>
			<div id="word_area1">
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	非會員也可參加活動　</span>
		<br>
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	獨立活動場地　　</span>	
		<br>
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	輕食小餐點、飲料提供</span>
		<br>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  <input type="button" onclick="location.href='activity.php'" id="apply" >
			</div>
			
			
			</div> 

	

	

 
			</div>
  
  <div id="activity2">
  
		<div id="left2">
  <h2 style="display:inline-block;font-size:18px;"> &nbsp &nbsp &nbsp《每到夏天我要去海邊＞ <br> &nbsp &nbsp &nbsp &nbsp &nbsp 西班牙海味料理製作</h2>
			<br> 
				<br>
			<div id="word_area1">
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	– 夏天西班牙蝦子沙拉　</span>
		<br>
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	- 干貝番茄蘆筍濃冷湯　　</span>	
		<br>
		<span class="word">&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp	- 豬排海鮮燉飯</span>
		<br>
&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  <input type="button" onclick="location.href='activity.php'" id="apply" >
			</div>
  
 
  
		</div>
  
			<div id="right2">
			
			<img id="rightbox1" style="width:304px;height:209px;margin-left:760px;margin-top:-208px;position:absolute;" src="pic2.JPG"> 
	
  
			</div>
  
  
  </div>
	</div>
</div>
</body>
</html>
